# postgres - production db
spring:
  application:
    name: userapi

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: embedded

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: userapi
    version: 1.0.0
    description: User Management REST API
    java-version: 17

#swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true