# postgres - production db
spring:
  application:
    name: userapi

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:userdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  security:
    user:
      name: ${SECURITY_USER_NAME}
      password: ${SECURITY_USER_PASSWORD}
      roles: ADMIN

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: userapi
    version: 1.0.0
    description: User Management REST API
    java-version: 17

# swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true